import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Happy Birthday <a href="https://nextjs.org">Jake!</a>
        </h1>
        <Image src="/B-DAY.svg" alt="bday-banner" width={300} height={300} />
        <p className={styles.description}>
          Scroll Down {' '}
          <code className={styles.code}>and enjoy!</code>
        </p>

        <div className={styles.grid}>
          <a href="#" className={styles.card}>
            <h2>I wanted to make you something  &rarr;</h2>
            <p>to celebrate!</p>
          </a>
          <Image src="/blowling-ball-01.svg" alt="" width={300} height={300} />
          <a href="#" className={styles.card}>
            <h2>Hooray Your 21 son! &rarr;</h2>
            <p>Click on each of these boxes & see an animation I made just for you my dude!</p>
          </a>
          <Image src="/bowling-turkey.svg" alt="" width={300} height={300} />
          <a
            href="#"
            className={styles.card}
          >
            <h2>More fun bowling animation! &rarr;</h2>
            <p>I just wanted you to know you were being thought of and make you something unique!</p>
          </a>
          <Image src="/bowling_pins.svg" alt="" width={300} height={300} />
          <a
            href="#"
            className={styles.card}
          >
            <h2>Happy Birthday my brother from another mother &rarr;</h2>
            <p>
              I hope you enjoy & get a few laughs from it at the very least....love ya buddy!
            </p>
          </a>
          <Image src="/img/bowling-duckpins1.svg" alt="" width={300} height={300} />
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
